spring:
  redis:
    host: ${REDIS_HOST:192.168.136.170}
    port: ${REDIS_PORT:6379}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
      - name: RequestRateLimiter
        args:
          redis-rate-limiter.replenishRate: 1  #令牌桶每秒填充平均速率
          redis-rate-limiter.burstCapacity: 3  #令牌桶总容量
          rate-limiter: "#{@defaultRedisRateLimiter}"  #SPEL表达式去的对应的bean
          key-resolver: "#{@remoteAddressKeyResolver}" #SPEL表达式去的对应的bean
      routes:
        - id: auth-center
          uri: lb://auth-center
          predicates:
            - Path=/auth-center/**
          filters:
            - GwSwaggerHeaderFilter
            - StripPrefix=1
        - id: admin-center
          uri: lb://admin-center
          predicates:
            - Path=/admin-center/**
          filters:
            - GwSwaggerHeaderFilter
            - StripPrefix=1
        - id: file-center
          uri: lb://file-center
          predicates:
            - Path=/file-center/**
          filters:
            - GwSwaggerHeaderFilter
            - StripPrefix=1


ignored: |
  /auth-center/**,/admin-center/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS