spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL:192.168.189.150}:${MYSQL_HOST:3306}/${MYSQL_DB:canteen-file-center}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT x
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/druid/*"
        reset-enable: false
        login-username: admin
        login-password: 123456

#MyBatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.dcy.file.model
  global-config:
    db-config:
      id-type: id_worker_str
  configuration:
    #不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: null


dcy:
  file-server:
    type: fastdfs
    fdfs:
      web-url: 192.168.136.170:8888
#fastDFS配置
fdfs:
  soTimeout: 1500
  connectTimeout: 600
  trackerList: 192.168.136.170:22122


# 密钥：AK 和 SK https://portal.qiniu.com/user/key
# bucketName 创建得存储空间名称
# endpoint 域名
# dcy:
#   file-server:
#     type: qiniu
#     oss:
#       access-key: B9r_DPgk9sCv-V6MMTyyi7KwHXdeQO0_FrUqNep0
#       accessKeySecret: 3y5qKrrNtJIaFgW1Axb-UbP2ERrYL9S7rzNCFcyk
#       endpoint: http://py9cmj9ml.bkt.clouddn.com/
#       bucketName: dcy-micro-service
#dcy:
#  file-server:
#    type: aliyun
#    oss:
#      access-key: LTAIMjvZWiXRuClW
#      accessKeySecret: YwJar7gkdZx3Q3Zk6TRuEAWaAz6n8y
#      endpoint: oss-cn-beijing.aliyuncs.com
#      bucketName: owenwangwen
#      domain: https://owenwangwen.oss-cn-beijing.aliyuncs.com

api:
  boot:
    swagger:
      title: Swagger2 文档
      description: "restful Api"
      version: "1.0"
      license: ""
      license-url: ""
      contact:
        name: dcy
        website: ""
        email: ""

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS